Repository athanggupte/CS-526-Game-Project, pull requests merged in 2023-10, with the labels that each got.

#6 feat: Add tutorial level
  Assets/Prefabs/Star.prefab
  Assets/Prefabs/Star.prefab.meta
  Assets/Scenes/Levels/Tutorial.unity
  Assets/Scenes/Levels/Tutorial.unity.meta
  Assets/Scripts/LevelEvents.cs
  Assets/Scripts/Star.cs
  Assets/Scripts/Star.cs.meta
  Assets/Scripts/StarController.cs
  Assets/Scripts/StarController.cs.meta
  ProjectSettings/TagManager.asset
Labels: enhancement, Priority: High

#12 issue: destroy star on collection
  Assets/Scripts/Star.cs
Labels: bug, Priority: High

#18 fix: Shooting Enemy shoots properly
  Assets/Prefabs/Aiming Player.prefab
  Assets/Prefabs/Missile.prefab
  Assets/Prefabs/Missile.prefab.meta
  Assets/Prefabs/Player.prefab
  Assets/Scenes/Deep-Test/Deep New Scene.unity
  Assets/Scenes/Levels/Level 1.unity
  Assets/Scripts/MissileEffector.cs
  Assets/Scripts/MissileEffector.cs.meta
  Assets/Scripts/ShootingEnemy.cs
Labels: bug, Priority: High

#14 Analytics setup
  Assets/Scenes/Deep-Test/Deep New Scene.unity
  Assets/Scenes/Levels/Level 1.unity
  Assets/Scenes/Levels/Tutorial Bomb.unity.meta
  Assets/Scenes/Levels/Tutorial.unity
  Assets/Scripts/ColorSwitchEffector.cs
  Assets/Scripts/DataCollector.cs
  Assets/Scripts/GoalController.cs
  Assets/Scripts/LevelTimer.cs
  Assets/Scripts/ZoneController.cs
  Assets/Scripts/ZoneController.cs.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement, Priority: High

#23 Fixed out of order initialization bug from Alpha Demo
  Assets/Scenes/Levels/Level 1.unity
  Assets/Scenes/Levels/Tutorial Bomb.unity
  Assets/Scripts/ColorEntity.cs
  Assets/Scripts/LevelColorController.cs
  Assets/Scripts/LevelEvents.cs
Labels: bug, Priority: High

#25 Fixed #20: Platform tile should remain white in all color states
  Assets/Scripts/ColorAdapter.cs
Labels: bug, Priority: Med

#38 Prevent Color mixing on overlapped tiles
  Assets/Scripts/LevelColorController.cs
  ProjectSettings/TagManager.asset
Labels: bug

#42 Feature/29 color bomb indicator
  Assets/Prefabs/Aiming Player.prefab
  Assets/Scripts/BombThrower.cs
  Assets/Scripts/MouseAiming.cs
Labels: enhancement, Priority: Med

#52 Cherry pick and merge Feature/restart button
  Assets/Prefabs/HUD.prefab
  Assets/Prefabs/HUD.prefab.meta
  Assets/Scenes/Levels/Level 1.unity
  Assets/Scenes/Levels/Level 2.unity
  Assets/Scenes/Levels/Tutorial Bomb.unity
  Assets/Scenes/Levels/Tutorial.unity
  Assets/Scenes/Overlay-LevelHUD.unity
  Assets/Scripts/HudOverlay.cs
  Assets/Scripts/HudOverlay.cs.meta
  Assets/Scripts/RestartGame.cs
  Assets/Scripts/RestartGame.cs.meta
  Assets/Sprites/restart-icon-32261.png
  Assets/Sprites/restart-icon-32261.png.meta
Labels: enhancement, Priority: High
