Repository athanggupte/CS-526-Game-Project, pull requests merged in 2023-11, with the labels that each got.

#57 Fixed incorrect color of tiles created by color bomb
  Assets/Prefabs/Level Color Controller.prefab
  Assets/Scripts/LevelColorController.cs
Labels: bug, Priority: High

#64 Added gunsCollectedCount
  Assets/Scripts/DataCollector.cs
Labels: enhancement

#65 Add the new scripts and UI to the player prefab
  Assets/Prefabs/Aiming Player.prefab
  Assets/Scenes/AG-tests/Test-FillableTiles.unity
Labels: bug

#66 Added toggle for weapon select and UI changes
  Assets/Prefabs/Color Bomb.prefab
  Assets/Scripts/WeaponController.cs
  Assets/Scripts/WeaponUIController.cs
Labels: enhancement

#67 Changed lmb-sprite with white version
  Assets/Sprites/lmb_sprite.png
  Assets/Sprites/lmb_sprite.png.meta
Labels: enhancement

#75 Attempt to force an interaction with the Color Blinder
  Assets/Scenes/Levels/Tutorial-2.unity
  Assets/Scripts/PathFollower.cs
  Assets/Scripts/TutorialColorBlinder.cs
  Assets/Scripts/TutorialColorBlinder.cs.meta
Labels: enhancement

#77 Feature/collectibles no destroy on full ammo
  Assets/Prefabs/Collectible Bomb.prefab
  Assets/Scenes/Levels/Level-1.unity
  Assets/Scripts/CollectibleBomb.cs
  Assets/Scripts/WeaponController.cs
Labels: enhancement, Priority: High

#78 Feature/dont show trajectory without ammo
  Assets/Scripts/BombWeaponHandler.cs
  Assets/Scripts/GunWeaponHandler.cs
Labels: enhancement, Priority: High

#82 Reduce the number of bullets
  Assets/Scenes/Levels/Level-3.unity
  Assets/Scripts/WeaponController.cs
  Assets/Scripts/WeaponUIController.cs
Labels: enhancement

#83 Add another medium level with the gun
  Assets/Scenes/Gautam-Test/Medium-Level.unity
  Assets/Scenes/Gautam-Test/Medium-Level.unity.meta
Labels: enhancement

#90 Reduce bomb splash alpha in Tutorial 2 animations
  Assets/Scenes/Levels/Tutorial-1.unity
Labels: enhancement

#88 Make keybinds more apparent to the players
  Assets/Scenes/Overlay-LevelHUD.unity
  Assets/Scripts/WeaponController.cs
  Assets/Scripts/WeaponUIController.cs
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
Labels: enhancement
